---

- name: Install mysql
  include: install-debian.yml
  when: ansible_distribution == 'Debian'
  tags: ['mysql-install']

- name: Install mysql
  include: install-ubuntu.yml
  when: ansible_distribution == 'Ubuntu'
  tags: ['mysql-install']
